### ISSUE TITLE
Support Version Ranges in smallrye-common-version

### ISSUE THREAD

**Issue by gastaldi** [smallrye/smallrye-common#54]
It would be nice to support version ranges as predicates from a `VersionScheme`

**Comment by gastaldi** [comment]
Maven has the `org.apache.maven.artifact.versioning.VersionRange`, which could be used as a basis

**Comment by dmlloyd** [comment]
Version ranges would already be supported in code using the standard Java comparator functions:

```java
                    Predicate<String> inRange = v -> VersionScheme.MAVEN.compare("1.0", v) >= 0 && VersionScheme.MAVEN.compare(v, "2.0") < 0;
```

Since it all uses `Comparator`, on the code side it would be more logical to add general comparator helpers than it would be to make special ones just for versions.

On the parsing side, the Maven version range syntax is very specific to Maven, so I think that would be better put into the upcoming Maven artifact utility that I'm working on.

Are there any use cases that I missed?

**Comment by gastaldi** [comment]
Ah-ha! Interesting, maybe it would be nice to have that strategy documented somewhere. I think that covers the use cases I'm looking for. 

I'm closing this issue for now.
